<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="RestAssuredFrameworksuite" duration-ms="2916" started-at="2019-11-04T00:19:27 CST" finished-at="2019-11-04T00:19:30 CST">
    <groups>
    </groups>
    <test name="RestAssuredtest" duration-ms="2916" started-at="2019-11-04T00:19:27 CST" finished-at="2019-11-04T00:19:30 CST">
      <class name="testCases.TC1_Get_AllEmployee">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.TC1_Get_AllEmployee@79be0360]" name="setup" is-config="true" duration-ms="65" started-at="2019-11-04T00:19:27 CST" finished-at="2019-11-04T00:19:27 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getAllEmployees()[pri:0, instance:testCases.TC1_Get_AllEmployee@79be0360]" name="getAllEmployees" is-config="true" duration-ms="2087" started-at="2019-11-04T00:19:27 CST" finished-at="2019-11-04T00:19:29 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployees -->
        <test-method status="FAIL" signature="checkresponsetime()[pri:0, instance:testCases.TC1_Get_AllEmployee@79be0360]" name="checkresponsetime" duration-ms="7" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:29 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [100] but found [1370]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [100] but found [1370]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:729)
at org.testng.Assert.assertEquals(Assert.java:739)
at testCases.TC1_Get_AllEmployee.checkresponsetime(TC1_Get_AllEmployee.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkresponsetime -->
        <test-method status="PASS" signature="checkstatusbody()[pri:0, instance:testCases.TC1_Get_AllEmployee@79be0360]" name="checkstatusbody" duration-ms="99" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:29 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusbody -->
        <test-method status="PASS" signature="checkstatuscode()[pri:0, instance:testCases.TC1_Get_AllEmployee@79be0360]" name="checkstatuscode" duration-ms="3" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:29 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatuscode -->
        <test-method status="FAIL" signature="checkstatusline()[pri:0, instance:testCases.TC1_Get_AllEmployee@79be0360]" name="checkstatusline" duration-ms="3" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:29 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [HTTP/1.1 200 OK]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [HTTP/1.1 200 OK]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at testCases.TC1_Get_AllEmployee.checkstatusline(TC1_Get_AllEmployee.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusline -->
      </class> <!-- testCases.TC1_Get_AllEmployee -->
      <class name="testCases.TC2_Post_Employee">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.TC2_Post_Employee@22a67b4]" name="setup" is-config="true" duration-ms="3" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:29 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="PostsingleEmployees()[pri:0, instance:testCases.TC2_Post_Employee@22a67b4]" name="PostsingleEmployees" is-config="true" duration-ms="512" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:29 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostsingleEmployees -->
        <test-method status="PASS" signature="checkresponsetime()[pri:0, instance:testCases.TC2_Post_Employee@22a67b4]" name="checkresponsetime" duration-ms="4" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:29 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkresponsetime -->
        <test-method status="PASS" signature="checkstatusbody()[pri:0, instance:testCases.TC2_Post_Employee@22a67b4]" name="checkstatusbody" duration-ms="51" started-at="2019-11-04T00:19:29 CST" finished-at="2019-11-04T00:19:30 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusbody -->
        <test-method status="PASS" signature="checkstatuscode()[pri:0, instance:testCases.TC2_Post_Employee@22a67b4]" name="checkstatuscode" duration-ms="7" started-at="2019-11-04T00:19:30 CST" finished-at="2019-11-04T00:19:30 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatuscode -->
        <test-method status="PASS" signature="checkstatusline()[pri:0, instance:testCases.TC2_Post_Employee@22a67b4]" name="checkstatusline" duration-ms="5" started-at="2019-11-04T00:19:30 CST" finished-at="2019-11-04T00:19:30 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusline -->
      </class> <!-- testCases.TC2_Post_Employee -->
    </test> <!-- RestAssuredtest -->
  </suite> <!-- RestAssuredFrameworksuite -->
</testng-results>
